### ISSUE TITLE
Multiple entries of same url when adding a list of links

### ISSUE THREAD

**Issue by TarantinoMariachi** [jshsakura/1fichier-dl#13]
When I try to add a list of 2 links, it adds 4, if I try to add 3 links it adds 9 links... basically he repeats each line for the number of elements we try to add. So its the number of lines ^ 2

**Comment by jshsakura** [comment]
Sorry for the late confirmation.
Let’s check the logic for adding to the list.

**Comment by jshsakura** [comment]
The problem of duplicate input has been corrected.
Thank you for reporting this issue. !!
