### ISSUE TITLE
다운로드 목록 중복

### ISSUE THREAD

**Issue by dc3000k** [jshsakura/1fichier-dl#14]
여러 url을 엔터로 구분해서 한 번에 추가하면 중복 목록이 생깁니다.

예를 들어 1,2,3 을 한 번에 추가하게되면 1,1,1,2,2,2,3,3,3 이렇게 추가되고 1,2,3,4,5를 추가하면 11111,22222,33333,44444,55555 이렇게 추가됩니다.

총 추가 개수만큼 각 url이 중복 추가됩니다

**Comment by jshsakura** [comment]
피드백 감사합니다.
너무 늦게 확인하고 말았네요.
해당 내용을 테스트해보도록 하겠습니다.

**Comment by jshsakura** [comment]
시간나실때 한번 확인 부탁드리겠습니다!
다운로드 목록에 앞뒤로 추가하던 문제가 수정되었습니다.
